### ISSUE TITLE
Fn lock

### ISSUE THREAD

**Issue by ghost** [metaquanta/soft_fn#1]
Would it be possible to lock the search/fn key to invert the relative actions? Or simply invert the action performed by the search/fn key? 
Basically when pressing the action keys to directly perform them, and when pressing the search+action keys perform the relative f# actions.

**Comment by metaquanta** [comment]
Anything is possible. If I understand you correctly (which is unlikely) that is what it currently does.
ie press search+F1 and get F1. Press F1 and get back.

**Comment by ghost** [comment]
I probably messed up something then, I had a previous configuration and there are probably some conflicts. Sorry.
Thanks!

**Comment by ghost** [comment]
I installed it on chell with a fresh debian bullseye install and actually got the issue I was talking about i.e. the opposite of what you described. Very strange.

**Comment by metaquanta** [comment]
Are you sure it's working at all? Run `evtest` (`apt install evtest` if missing). "Virtual keyboard (soft-fn)" should be in the list of devices. If it's there, select it to see the codes it reports.
If it's working, something higher level must be remapping the F-keys back (xkb/xinput/etc).

**Comment by ghost** [comment]
I installed Arch on the chell now (couldn't enable audio on Debian) and soft fn is working as supposed. Thanks for the help!
